# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/obiwan/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/obiwan

PRODUCT_COPY_FILES += \
    vendor/asus/obiwan/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml

PRODUCT_PACKAGES += \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    com.android.hotwordenrollment.common.util
